---
title: "All Histograms in One Plot (for each chromosome)"
author: "Abby Coleman"
date: "`r Sys.Date()`"
output: 
  html_document:
      keep_md: yes
---

```{r setup, include=FALSE}
#add packages
library(here)
library(tidyverse)
library(dplyr)
library(ggridges)
library(ggplot2)
#source other files
source(here("scripts", "functions.R"))
#set kniter options
knitr::opts_chunk$set(echo = TRUE)
```

# Depth Histograms by Chromosome


```{r read_hist_data, echo = FALSE, warning = FALSE, dev = "png"}
file_list2 <- list.files("/Users/acoleman/Documents/GitHub/vaidhy_quick_histogram/20230605_state_histograms/data_input/unzipped", full.names = TRUE)
  # 
  # file.path("/Users/acoleman/Documents/GitHub/vaidhy_quick_histogram", ))
  # 
  # here("20230605_state_histograms", "data_input", "unzipped"), full.names = TRUE)

#read in data
df2 <- file_list %>%
  map_df(read_data) %>%
  #rename columns
  rename(chrom = V1,
         depth = V2)
# %>%
#   #filter out chromosomes X, Y, and M
#   filter(!(chrom %in% c("chrX", "chrY", "chrM")))
```


```{r make_hists, echo = FALSE, warning = FALSE, message = FALSE}
df2 <- df2 %>%
  group_by(chrom) %>%
  nest()

ridge_hists <- apply(df2, 1, make_ridge_hists)

print(ridge_hists)
```